# Generated by Django 4.2 on 2023-04-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavoriteadvertisements',
            old_name='created_at',
            new_name='added_at',
        ),
    ]
