# Generated by Django 4.2 on 2023-04-21 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0002_rename_created_at_userfavoriteadvertisements_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoriteadvertisements',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.advertisement'),
        ),
        migrations.AlterUniqueTogether(
            name='userfavoriteadvertisements',
            unique_together={('user', 'advertisement')},
        ),
    ]
